### ISSUE TITLE
stress配置界面报错

### ISSUE THREAD

**Issue by xqzw123** [linyimin0812/mybatis-sql-viewer#13]
报错信息如下：

```
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "javax.swing.table.DefaultTableModel.getValueAt(int, int)" is null
	at io.github.linyimin.plugin.utils.MockTypeUtils.initStressMockColumnValues(MockTypeUtils.java:79)
	at io.github.linyimin.plugin.utils.MockTypeUtils.addMockColumns(MockTypeUtils.java:48)
	at io.github.linyimin.plugin.ui.SqlStressTabbedPane.generateMockConfigTable(SqlStressTabbedPane.java:622)
	at io.github.linyimin.plugin.ui.SqlStressTabbedPane.access$700(SqlStressTabbedPane.java:65)
	at io.github.linyimin.plugin.ui.SqlStressTabbedPane$2.run(SqlStressTabbedPane.java:537)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by linyimin0812** [comment]
stress界面相关的配置可以发一下嘛？我看看能不能复现

**Comment by xqzw123** [comment]
你好，stress配置界面即报错。其他功能正常



***@***.***
 
发件人： linyimin
发送时间： 2023-11-20 22:28
收件人： linyimin0812/mybatis-sql-viewer
抄送： xqzw123; Author
主题： Re: [linyimin0812/mybatis-sql-viewer] stress配置界面报错 (Issue #13)
stress界面相关的配置可以发一下嘛？我看看能不能复现

**Comment by kangcaiyuan** [comment]
我也报这个错误， 感觉这个插件挺好，希望作者完善啊。
